### ISSUE TITLE
New tox environment docstyle

### ISSUE THREAD

**Issue by leliel12** [ngrion/apode#22]
Implementar el test pydocstyle en tox, y agregarlo a travis. Documentar TODO apode, lo que aun no este bien definido, moverlo a una carpeta draft **aparte** del código

```ini
[testenv:docstyle]
deps = pydocstyle
commands =
    pydocstyle apode --convention=numpy
```

**Comment by ngrion** [comment]
Estos warnings surgen al correr Sphinx;

WARNING: missing attribute mentioned in :members: or __all__: module apode, attribute Apode
checking consistency... D:\GitHub\apode\docs\source\modules.rst: WARNING: document isn't included in any toctree

**Comment by ngrion** [comment]
readthedocs no compila, por este error:

ModuleNotFoundError: No module named 'sphinxcontrib.napoleon'

sugiere crear un .readthedocs.yml
