### ISSUE TITLE
módulo datasets

### ISSUE THREAD

**Issue by leliel12** [ngrion/apode#23]
implementar el módulo `datasets` que permita crear ApodeData de diferentes formas.

Lo primero es implementar los métodos `make_<DISTRIBUTION>` que deben aceptar siempte, paárametros de la distribucion, un tamaño del set de datos y una semilla. Por ejemplo

```python
def make_pareto(a=5, c=200, size=100, seed=None):
      random = np.random.RandomState(seed=seed)
      y = pd.DataFrame(
          {"y": 200 * rg.pareto(a=5, size=size)})
      return ApodeData(df1, varx="y")
```

Tener en cuenta que segun los ejemplos del actual `distributions.py` la plat se guarda en la columna "y", mientras que en los fixtures usamos la columna X. Habria que unificar. y asignar un nombre mejor a "varx" capaz que `income_column` o `analysis_column`

Tambien habria que implementar los fixtures (o reemplazarlos dado que hacen lo mismo) con este nuevo modulo cuando este listo.

**Comment by ngrion** [comment]
Están implementado los make_"distribution"
Además se agregan 6 casos no random: make_linear, etc

**Comment by ngrion** [comment]
cómo invocar? implementar algo así?

`ap = ApodeData.data.pareto()`

**Comment by leliel12** [comment]
No para nada... ApodaData son tus estructuras de datos, vos tenes el modulo datasets (que si pensas es totalmente independiente). Lo que uno espera es usarlo de esta forma

```pyhton
from apode import datasets
apd = datasets.make_normal()
```

ALSO

Veo que hay muchos valores harcodeados, por ejemplo en 

https://github.com/ngrion/apode/blob/30ac1b24e949eb40dd4cf1106b32640fe7f114a2/apode/datasets.py#L148-L160

Podria definirse el significado de 1.2 y ofrecerse como parametro

Finalmentes

Estan usando mucho "listas" (`list`) Eso esta re mal, por que estan regalando performance. Usen mas el stack cientifico
por jemplo la linea 

```python
y = list(range(1, size + 1))
```
Puede reescribirse como

```python
y = np.arange(1, size+1)
```

Y ya la tenes en numpy
