### ISSUE TITLE
Plots

### ISSUE THREAD

**Issue by leliel12** [ngrion/apode#24]
Implementar módulo y tests para plot. 

Copiar de las slides de clases y de la imagen adjunta. Acordarse de como tratar los ejex ( `ax`) como se explico en clase.

![image](https://user-images.githubusercontent.com/299010/97752439-c4ac1b80-1ad2-11eb-87cd-aafb573a01e7.png)

**Comment by ngrion** [comment]
modulo implementado, falta ejes y test
lorenz, pen y tip se dividen en dos funciones: datos y graficos. Esto es util para cuando se quiera superponer varios graficos. ver cómo implementar. 
en notebook tutorial se muestra uso
