### ISSUE TITLE
Implementar getitem

### ISSUE THREAD

**Issue by leliel12** [ngrion/apode#35]
Actualmente la funcionalidad de eliminar filar y columnas de `pandas.DataFrame` no esta implementado.

Implementar el método

```python
def __getitem__(self, slice):
        df = self.data.__getitem__(silce)
        return ApodeData(df, income_column=self.income_column)
```

Probar los tests de cortado de filas, y de columnas. Garantizar que al tratar de cortar la columna de income. Todo explota (dado que existe un validador, esto deberia estar sucediendo si mas codigo

**Comment by ngrion** [comment]
implementado. test:

"""'python
n = 10
ad1 = ApodeData({'x':np.arange(0,n),'y': np.arange(0,n)*10},income_column='x')

# test 1
ad2 = ApodeData({'x':np.arange(0,2*n),'y': np.arange(0,2*n)*10},income_column='x')
ad3 = ad2[:n]
t1 = all(ad1.data==ad3.data)

# test 2
ad2 = ApodeData({'x':np.arange(0,n)},income_column='x')
ad3 = ad1['x']
t2 = all(ad3.data==ad2.data)

# test 3
ad2 = ApodeData({'x':np.arange(0,2*n),'y': np.arange(0,2*n)*10},income_column='x')
ad3 = ad2[ad2.x<n]
t3 = all(ad1.data==ad3.data)

# test 4
try:
    t4 = False
    ad3 = ad1['y'] 
except:
    t4 = True
           
test = t1 and t2 and t3 and t4
test

"""

**Comment by leliel12** [comment]
No se usa try y excep para test hay que hacer assert y pytest.raises. el
codigo no tiene que ser ingenioso. Tiene que ser simple
